[tool.isort]
profile="black"
line_length = 120
skip = ["src", "venv", ".venv", ".aws-sam"]

[tool.black]
line-length = 120
target-version = ["py311", ]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.aws-sam
    | venv
    | src
  )/
)
'''

[tool.coverage.run]
omit = [
    "server/main.py",
    "server/types.py",
    "server/reset_password_user.py",
    "server/initial_data.py",
    "server/version.py",
    "server/forms/*",
    "server/api/endpoints/login.py"
    ]
