"""empty message

Revision ID: 1cf62bad0d77
Revises: 338e6fa88d5e
Create Date: 2020-08-11 20:54:36.480710

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1cf62bad0d77"
down_revision = "338e6fa88d5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("cannabis", sa.Boolean(), nullable=True))
    op.drop_index("ix_products_name", table_name="products")
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.create_index("ix_products_name", "products", ["name"], unique=True)
    op.drop_column("categories", "cannabis")
    # ### end Alembic commands ###
