"""empty message

Revision ID: 1e4faa3cf4bd
Revises: afacc23c2670
Create Date: 2019-11-27 09:22:33.188541

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e4faa3cf4bd"
down_revision = "afacc23c2670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_kind_images_id", table_name="kind_images")
    op.drop_index("ix_kind_images_kind_id", table_name="kind_images")
    op.drop_table("kind_images")
    op.add_column("kinds", sa.Column("image_1", sa.String(length=255), nullable=True))
    op.add_column("kinds", sa.Column("image_2", sa.String(length=255), nullable=True))
    op.add_column("kinds", sa.Column("image_3", sa.String(length=255), nullable=True))
    op.add_column("kinds", sa.Column("image_4", sa.String(length=255), nullable=True))
    op.add_column("kinds", sa.Column("image_5", sa.String(length=255), nullable=True))
    op.add_column("kinds", sa.Column("image_6", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_kinds_image_1"), "kinds", ["image_1"], unique=True)
    op.create_index(op.f("ix_kinds_image_2"), "kinds", ["image_2"], unique=True)
    op.create_index(op.f("ix_kinds_image_3"), "kinds", ["image_3"], unique=True)
    op.create_index(op.f("ix_kinds_image_4"), "kinds", ["image_4"], unique=True)
    op.create_index(op.f("ix_kinds_image_5"), "kinds", ["image_5"], unique=True)
    op.create_index(op.f("ix_kinds_image_6"), "kinds", ["image_6"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kinds_image_6"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_image_5"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_image_4"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_image_3"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_image_2"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_image_1"), table_name="kinds")
    op.drop_column("kinds", "image_6")
    op.drop_column("kinds", "image_5")
    op.drop_column("kinds", "image_4")
    op.drop_column("kinds", "image_3")
    op.drop_column("kinds", "image_2")
    op.drop_column("kinds", "image_1")
    op.create_table(
        "kind_images",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("modified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("kind_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("order_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["kind_id"], ["kinds.id"], name="kind_images_kind_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="kind_images_pkey"),
    )
    op.create_index("ix_kind_images_kind_id", "kind_images", ["kind_id"], unique=False)
    op.create_index("ix_kind_images_id", "kind_images", ["id"], unique=False)
    # ### end Alembic commands ###
