"""License Update.

Revision ID: 86687aacf1dc
Revises: 5bcb68c2a860
Create Date: 2023-10-17 15:45:40.622575

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "86687aacf1dc"
down_revision = "5bcb68c2a860"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "licenses",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("improviser_user", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_licenses_id"), "licenses", ["id"], unique=False)
    op.create_index(op.f("ix_licenses_order_id"), "licenses", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_licenses_order_id"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_id"), table_name="licenses")
    op.drop_table("licenses")
    # ### end Alembic commands ###
