"""added pricelist positions.

Revision ID: 11b434c7dc5a
Revises: 86687aacf1dc
Create Date: 2023-12-01 20:00:54.487160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11b434c7dc5a"
down_revision = "86687aacf1dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("pricelist_column", sa.String(), nullable=True))
    op.add_column("categories", sa.Column("pricelist_row", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "pricelist_row")
    op.drop_column("categories", "pricelist_column")
    # ### end Alembic commands ###
