"""License Drop.

Revision ID: 5bcb68c2a860
Revises: 84ca7a4fad8e
Create Date: 2023-10-17 15:42:49.710211

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5bcb68c2a860"
down_revision = "84ca7a4fad8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_licenses_id", table_name="licenses")
    op.drop_index("ix_licenses_name", table_name="licenses")
    op.drop_table("licenses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "licenses",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="licenses_pkey"),
    )
    op.create_index("ix_licenses_name", "licenses", ["name"], unique=True)
    op.create_index("ix_licenses_id", "licenses", ["id"], unique=False)
    # ### end Alembic commands ###
