"""Shop config version.

Revision ID: 9fec94fb45a9
Revises: c61e89a89bac
Create Date: 2024-09-13 17:07:19.220647

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fec94fb45a9"
down_revision = "c61e89a89bac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("config_version", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "config_version")
    # ### end Alembic commands ###
