"""new label on products.

Revision ID: 35a9b4add7a2
Revises: 9fec94fb45a9
Create Date: 2024-10-15 12:32:31.790422

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35a9b4add7a2"
down_revision = "9fec94fb45a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("new_product", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "new_product")
    # ### end Alembic commands ###
