"""Language coded category images.

Revision ID: c61e89a89bac
Revises: aad423d59048
Create Date: 2024-09-06 14:05:19.633682

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c61e89a89bac"
down_revision = "aad423d59048"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("main_image", sa.String(length=255), nullable=True))
    op.add_column("categories", sa.Column("alt1_image", sa.String(length=255), nullable=True))
    op.add_column("categories", sa.Column("alt2_image", sa.String(length=255), nullable=True))
    op.drop_index("ix_categories_image_1", table_name="categories")
    op.drop_index("ix_categories_image_2", table_name="categories")
    op.create_index(op.f("ix_categories_alt1_image"), "categories", ["alt1_image"], unique=False)
    op.create_index(op.f("ix_categories_alt2_image"), "categories", ["alt2_image"], unique=False)
    op.create_index(op.f("ix_categories_main_image"), "categories", ["main_image"], unique=False)
    op.drop_column("categories", "image_2")
    op.drop_column("categories", "image_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("image_1", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("categories", sa.Column("image_2", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_categories_main_image"), table_name="categories")
    op.drop_index(op.f("ix_categories_alt2_image"), table_name="categories")
    op.drop_index(op.f("ix_categories_alt1_image"), table_name="categories")
    op.create_index("ix_categories_image_2", "categories", ["image_2"], unique=False)
    op.create_index("ix_categories_image_1", "categories", ["image_1"], unique=False)
    op.drop_column("categories", "alt2_image")
    op.drop_column("categories", "alt1_image")
    op.drop_column("categories", "main_image")
    # ### end Alembic commands ###
