"""added shop type field.

Revision ID: 5476ce1082c1
Revises: 757168fc0571
Create Date: 2024-10-29 15:57:00.469637

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "5476ce1082c1"
down_revision = "757168fc0571"
branch_labels = None
depends_on = None

shop_type_enum = ENUM("BASIC", "BASIC_PLUS", "CUSTOM", "CUSTOM_PLUS", name="shoptype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    shop_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("shops", sa.Column("shop_type", shop_type_enum, server_default="BASIC", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "shop_type")
    # ### end Alembic commands ###
