"""Added Stripe keys to ShopTable.

Revision ID: 2ededc6a6553
Revises: f113c8f56714
Create Date: 2024-08-15 15:00:32.883425

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ededc6a6553"
down_revision = "f113c8f56714"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("stripe_secret_key", sa.String(length=255), nullable=True))
    op.add_column("shops", sa.Column("stripe_public_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "stripe_public_key")
    op.drop_column("shops", "stripe_secret_key")
    # ### end Alembic commands ###
