"""Added featured product boolean.

Revision ID: aad423d59048
Revises: 2ededc6a6553
Create Date: 2024-08-23 14:21:20.998385

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aad423d59048"
down_revision = "2ededc6a6553"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("featured", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "featured")
    # ### end Alembic commands ###
