"""Restored old order fields.

Revision ID: 7ae482eb2f95
Revises: 1aec250f9927
Create Date: 2024-07-17 15:50:56.572859

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ae482eb2f95"
down_revision = "1aec250f9927"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("total", sa.Float(), nullable=True))
    op.add_column("orders", sa.Column("status", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("completed_by", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.add_column("orders", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.create_foreign_key(None, "orders", "users", ["completed_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "completed_at")
    op.drop_column("orders", "completed_by")
    op.drop_column("orders", "status")
    op.drop_column("orders", "total")
    # ### end Alembic commands ###
