"""add order_number to products.

Revision ID: fc7487025229
Revises: 4fa16ebf6035
Create Date: 2024-11-12 12:17:50.625627

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc7487025229"
down_revision = "4fa16ebf6035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("order_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "order_number")
    # ### end Alembic commands ###
