"""Add tax to products.

Revision ID: c9f7550d11bb
Revises: 1b485cfea981
Create Date: 2024-05-21 20:05:05.971563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9f7550d11bb"
down_revision = "1b485cfea981"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("shop_id", sa.UUID(), nullable=True))
    op.add_column("products", sa.Column("price", sa.Float(), nullable=False))
    op.add_column("products", sa.Column("tax_category", sa.String(length=20), nullable=True))
    op.add_column("products", sa.Column("discounted_price", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("discounted_from", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("discounted_to", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_products_shop_id"), "products", ["shop_id"], unique=False)
    op.create_foreign_key(None, "products", "shops", ["shop_id"], ["id"])
    op.add_column("shops", sa.Column("vat_standard", sa.Float(), nullable=False))
    op.add_column("shops", sa.Column("vat_lower_1", sa.Float(), nullable=False))
    op.add_column("shops", sa.Column("vat_lower_2", sa.Float(), nullable=False))
    op.add_column("shops", sa.Column("vat_lower_3", sa.Float(), nullable=False))
    op.add_column("shops", sa.Column("vat_special", sa.Float(), nullable=False))
    op.add_column("shops", sa.Column("vat_zero", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "vat_zero")
    op.drop_column("shops", "vat_special")
    op.drop_column("shops", "vat_lower_3")
    op.drop_column("shops", "vat_lower_2")
    op.drop_column("shops", "vat_lower_1")
    op.drop_column("shops", "vat_standard")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_index(op.f("ix_products_shop_id"), table_name="products")
    op.drop_column("products", "discounted_to")
    op.drop_column("products", "discounted_from")
    op.drop_column("products", "discounted_price")
    op.drop_column("products", "tax_category")
    op.drop_column("products", "price")
    op.drop_column("products", "shop_id")
    # ### end Alembic commands ###
