"""internal-and-external-shop-urls.

Revision ID: e01e0b0ee64a
Revises: e634c8a1c704
Create Date: 2025-03-11 15:11:24.453952

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e01e0b0ee64a"
down_revision = "e634c8a1c704"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("internal_url", sa.String(length=255), server_default="", nullable=True))
    op.add_column("shops", sa.Column("external_url", sa.String(length=255), server_default="", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "external_url")
    op.drop_column("shops", "internal_url")
    # ### end Alembic commands ###
