"""removed users and roles.

Revision ID: 6066e68a587d
Revises: eec1442a92cf
Create Date: 2025-07-19 16:49:42.734967

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6066e68a587d"
down_revision = "eec1442a92cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_roles_users_id", table_name="roles_users")
    op.drop_table("roles_users")
    op.drop_index("ix_shops_users_id", table_name="shops_users")
    op.drop_table("shops_users")
    op.drop_index("ix_roles_id", table_name="roles")
    op.drop_table("roles")
    op.drop_constraint("orders_completed_by_fkey", "orders", type_="foreignkey")
    op.drop_column("orders", "completed_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("completed_by", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key("orders_completed_by_fkey", "orders", "users", ["completed_by"], ["id"])
    op.create_table(
        "shops_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("shop_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name="shops_users_shop_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="shops_users_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="shops_users_pkey"),
    )
    op.create_index("ix_shops_users_id", "shops_users", ["id"], unique=False)
    op.create_table(
        "roles_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name="roles_users_role_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="roles_users_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="roles_users_pkey"),
    )
    op.create_index("ix_roles_users_id", "roles_users", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
        sa.UniqueConstraint("name", name="roles_name_key"),
    )
    op.create_index("ix_roles_id", "roles", ["id"], unique=False)
    # ### end Alembic commands ###
