"""discord_webhook_on_shop.

Revision ID: 18a302939a23
Revises: ec4ba0f258b8
Create Date: 2025-04-26 14:14:46.936803

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18a302939a23"
down_revision = "ec4ba0f258b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("discord_webhook", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "discord_webhook")
    # ### end Alembic commands ###
