"""added stock field on products.

Revision ID: cac5979b07e9
Revises: eec1442a92cf
Create Date: 2025-11-29 16:20:21.613623

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cac5979b07e9"
down_revision = "eec1442a92cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("stock", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "stock")
    # ### end Alembic commands ###
