"""hostname on shop table.

Revision ID: 734ec43b1bce
Revises: e5343c704a93
Create Date: 2025-01-14 17:08:47.749053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "734ec43b1bce"
down_revision = "e5343c704a93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("hostname", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "shops", ["hostname"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shops", type_="unique")
    op.drop_column("shops", "hostname")
    # ### end Alembic commands ###
