"""expanded_shop_type.

Revision ID: e634c8a1c704
Revises: db0ee0bc1435
Create Date: 2025-02-06 14:31:37.175160

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e634c8a1c704"
down_revision = "db0ee0bc1435"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops", sa.Column("shop_type", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False)
    )
    op.execute(sa.text("""UPDATE shops SET config = '{}' WHERE config IS NULL"""))
    op.alter_column(
        "shops",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default="{}",
        default="{}",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shops", "config", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    op.drop_column("shops", "shop_type")
    # ### end Alembic commands ###
