"""create FAQ table.

Revision ID: eec1442a92cf
Revises: 18a302939a23
Create Date: 2025-06-13 16:20:27.525773

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from server.db.models import UtcTimestamp

# revision identifiers, used by Alembic.
revision = "eec1442a92cf"
down_revision = "18a302939a23"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text("uuid_generate_v4()"), nullable=False
        ),
        sa.Column("question", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", UtcTimestamp(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "modified_at", UtcTimestamp(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faq_id"), "faq", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faq_id"), table_name="faq")
    op.drop_table("faq")
    # ### end Alembic commands ###
