"""extra_product_attributes.

Revision ID: 8e3b3cdb84c9
Revises: e5343c704a93
Create Date: 2025-02-04 14:06:47.777716

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8e3b3cdb84c9"
down_revision = "e5343c704a93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "attributes")
    # ### end Alembic commands ###
