"""add api_keys table.

Revision ID: 2d3b9531fc47
Revises: 8e3b3cdb84c9
Create Date: 2025-02-16 13:12:53.839180

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from server.db import UtcTimestamp

# revision identifiers, used by Alembic.
revision = "2d3b9531fc47"
down_revision = "8e3b3cdb84c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text("uuid_generate_v4()"), nullable=False
        ),
        sa.Column("shop_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column(
            "created_at", UtcTimestamp(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column("revoked_at", UtcTimestamp(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_hashed_key"), "api_keys", ["hashed_key"], unique=True)
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(op.f("ix_api_keys_shop_id"), "api_keys", ["shop_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_shop_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_hashed_key"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
