"""drop_old_shop_type.

Revision ID: db0ee0bc1435
Revises: 8e3b3cdb84c9
Create Date: 2025-02-06 14:22:31.861695

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "db0ee0bc1435"
down_revision = "8e3b3cdb84c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "shop_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops",
        sa.Column(
            "shop_type",
            postgresql.ENUM("BASIC", "BASIC_PLUS", "CUSTOM", "CUSTOM_PLUS", name="shoptype"),
            server_default=sa.text("'BASIC'::shoptype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
