"""Remove old attributes.

Revision ID: bff2303828ce
Revises: a1b2c3d4e5f6
Create Date: 2026-01-29 20:00:53.141593

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bff2303828ce"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    return # For now the old stuff can stay, removing this field will add some extra work and i dont want that for the MVP version of the new attributes

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attribute_options", "value_key", existing_type=sa.VARCHAR(length=60), nullable=True)
    op.alter_column("attributes", "name", existing_type=sa.VARCHAR(length=60), nullable=True)
    op.drop_index(
        "pav_attr_option_idx", table_name="product_attribute_values", postgresql_where="(option_id IS NOT NULL)"
    )
    op.drop_index(
        "pav_attr_value_idx", table_name="product_attribute_values", postgresql_where="(value_text IS NOT NULL)" #Value text isnt a thing in the mvp
    )
    # ### end Alembic commands ###

    with op.batch_alter_table("products") as batch_op:
        batch_op.drop_column("attributes")


def downgrade() -> None:
    return # For now the old stuff can stay, removing this field will add some extra work and i dont want that for the MVP version of the new attributes

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "pav_attr_value_idx",
        "product_attribute_values",
        ["attribute_id"],
        unique=False,
        postgresql_where="(value_text IS NOT NULL)",  #Value text isnt a thing in the mvp
    )
    op.create_index(
        "pav_attr_option_idx",
        "product_attribute_values",
        ["attribute_id", "option_id"],
        unique=False,
        postgresql_where="(option_id IS NOT NULL)",
    )
    op.alter_column("attributes", "name", existing_type=sa.VARCHAR(length=60), nullable=False)
    op.alter_column("attribute_options", "value_key", existing_type=sa.VARCHAR(length=60), nullable=False)
    # ### end Alembic commands ###

    with op.batch_alter_table("products") as batch_op:
        batch_op.add_column(sa.Column("attributes", sa.dialects.postgresql.JSONB(), nullable=True))
