"""empty message

Revision ID: 33cfa1e5d315
Revises: 4180c1718447
Create Date: 2019-11-21 23:27:59.528143

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "33cfa1e5d315"
down_revision = "4180c1718447"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kind_images",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("kind_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["kind_id"], ["kinds.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kind_images_id"), "kind_images", ["id"], unique=False)
    op.create_index(op.f("ix_kind_images_kind_id"), "kind_images", ["kind_id"], unique=False)
    op.add_column("kinds", sa.Column("modified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kinds", "modified_at")
    op.drop_index(op.f("ix_kind_images_kind_id"), table_name="kind_images")
    op.drop_index(op.f("ix_kind_images_id"), table_name="kind_images")
    op.drop_table("kind_images")
    # ### end Alembic commands ###
