"""empty message

Revision ID: 38b7e9d236b4
Revises: baa58f9b173a
Create Date: 2020-09-29 14:37:57.433352

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "38b7e9d236b4"
down_revision = "baa58f9b173a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("completed_by", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "orders", "user", ["completed_by"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "completed_by")
    # ### end Alembic commands ###
