"""Add images for subcategories

Revision ID: 4f37d89acc0d
Revises: 86f5375d4011
Create Date: 2021-06-12 03:07:12.614044

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f37d89acc0d"
down_revision = "86f5375d4011"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("image_1", sa.String(length=255), nullable=True))
    op.add_column("categories", sa.Column("image_2", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_categories_image_1"), "categories", ["image_1"], unique=True)
    op.create_index(op.f("ix_categories_image_2"), "categories", ["image_2"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_image_2"), table_name="categories")
    op.drop_index(op.f("ix_categories_image_1"), table_name="categories")
    op.drop_column("categories", "image_2")
    op.drop_column("categories", "image_1")
    # ### end Alembic commands ###
