"""empty message

Revision ID: 724afaa1a186
Revises: 7f1d088444e7
Create Date: 2020-11-24 15:15:48.094874

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "724afaa1a186"
down_revision = "7f1d088444e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_categories",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("shop_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("order_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_main_categories_description"), "main_categories", ["description"], unique=True)
    op.create_index(op.f("ix_main_categories_id"), "main_categories", ["id"], unique=False)
    op.create_index(op.f("ix_main_categories_shop_id"), "main_categories", ["shop_id"], unique=False)
    op.add_column("categories", sa.Column("main_category_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f("ix_categories_main_category_id"), "categories", ["main_category_id"], unique=False)
    op.create_foreign_key(None, "categories", "main_categories", ["main_category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_index(op.f("ix_categories_main_category_id"), table_name="categories")
    op.drop_column("categories", "main_category_id")
    op.drop_index(op.f("ix_main_categories_shop_id"), table_name="main_categories")
    op.drop_index(op.f("ix_main_categories_id"), table_name="main_categories")
    op.drop_index(op.f("ix_main_categories_description"), table_name="main_categories")
    op.drop_table("main_categories")
    # ### end Alembic commands ###
