"""empty message

Revision ID: 75c79b52c3b4
Revises: 1deb625f8c2e
Create Date: 2019-09-07 00:43:46.969516

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "75c79b52c3b4"
down_revision = "1deb625f8c2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kinds_to_flavors",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("flavor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["flavor_id"], ["flavors.id"]),
        sa.ForeignKeyConstraint(["kind_id"], ["kinds.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kinds_to_flavors_flavor_id"), "kinds_to_flavors", ["flavor_id"], unique=False)
    op.create_index(op.f("ix_kinds_to_flavors_id"), "kinds_to_flavors", ["id"], unique=False)
    op.create_index(op.f("ix_kinds_to_flavors_kind_id"), "kinds_to_flavors", ["kind_id"], unique=False)
    op.drop_index("ix_flavors_to_tags_flavor_id", table_name="flavors_to_tags")
    op.drop_index("ix_flavors_to_tags_id", table_name="flavors_to_tags")
    op.drop_index("ix_flavors_to_tags_kind_id", table_name="flavors_to_tags")
    op.drop_table("flavors_to_tags")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flavors_to_tags",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("kind_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("flavor_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["flavor_id"], ["flavors.id"], name="flavors_to_tags_flavor_id_fkey"),
        sa.ForeignKeyConstraint(["kind_id"], ["kinds.id"], name="flavors_to_tags_kind_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="flavors_to_tags_pkey"),
    )
    op.create_index("ix_flavors_to_tags_kind_id", "flavors_to_tags", ["kind_id"], unique=False)
    op.create_index("ix_flavors_to_tags_id", "flavors_to_tags", ["id"], unique=False)
    op.create_index("ix_flavors_to_tags_flavor_id", "flavors_to_tags", ["flavor_id"], unique=False)
    op.drop_index(op.f("ix_kinds_to_flavors_kind_id"), table_name="kinds_to_flavors")
    op.drop_index(op.f("ix_kinds_to_flavors_id"), table_name="kinds_to_flavors")
    op.drop_index(op.f("ix_kinds_to_flavors_flavor_id"), table_name="kinds_to_flavors")
    op.drop_table("kinds_to_flavors")
    # ### end Alembic commands ###
