"""empty message

Revision ID: 783682226c9b
Revises: b882b9ab026c
Create Date: 2019-10-19 10:07:14.923441

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "783682226c9b"
down_revision = "b882b9ab026c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prices", "internal_product_id", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prices", "internal_product_id", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=True
    )
    # ### end Alembic commands ###
