"""empty message

Revision ID: 78a36d111067
Revises: 38b7e9d236b4
Create Date: 2020-10-09 13:28:17.677391

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78a36d111067"
down_revision = "38b7e9d236b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_tables",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("shop_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_tables_id"), "shop_tables", ["id"], unique=False)
    op.create_index(op.f("ix_shop_tables_shop_id"), "shop_tables", ["shop_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shop_tables_shop_id"), table_name="shop_tables")
    op.drop_index(op.f("ix_shop_tables_id"), table_name="shop_tables")
    op.drop_table("shop_tables")
    # ### end Alembic commands ###
