"""empty message

Revision ID: 7f1d088444e7
Revises: 78a36d111067
Create Date: 2020-10-09 15:56:01.365057

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7f1d088444e7"
down_revision = "78a36d111067"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("table_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "orders", "shop_tables", ["table_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "table_id")
    # ### end Alembic commands ###
