"""empty message

Revision ID: 94987a18f795
Revises: eaabfa90f65b
Create Date: 2019-09-10 12:41:01.747282

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94987a18f795"
down_revision = "eaabfa90f65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("piece", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "piece")
    # ### end Alembic commands ###
