"""empty message

Revision ID: 9d8fc446eec1
Revises: cb34c1d864fc
Create Date: 2019-09-18 00:45:49.930785

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d8fc446eec1"
down_revision = "cb34c1d864fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops_to_price", sa.Column("kind_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f("ix_shops_to_price_kind_id"), "shops_to_price", ["kind_id"], unique=False)
    op.create_foreign_key(None, "shops_to_price", "kinds", ["kind_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shops_to_price", type_="foreignkey")
    op.drop_index(op.f("ix_shops_to_price_kind_id"), table_name="shops_to_price")
    op.drop_column("shops_to_price", "kind_id")
    # ### end Alembic commands ###
