"""empty message

Revision ID: b34e3e216a68
Revises: 724afaa1a186
Create Date: 2020-11-24 23:40:47.760875

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b34e3e216a68"
down_revision = "724afaa1a186"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("name_en", sa.String(length=255), nullable=True))
    op.add_column("main_categories", sa.Column("name_en", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("main_categories", "name_en")
    op.drop_column("categories", "name_en")
    # ### end Alembic commands ###
