"""empty message

Revision ID: b401271d2d81
Revises: 692f4b3203d8
Create Date: 2022-05-24 19:10:32.217878

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b401271d2d81"
down_revision = "692f4b3203d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("allowed_ips", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "allowed_ips")
    # ### end Alembic commands ###
