"""empty message

Revision ID: b98ea2a3d8ea
Revises: 1e4faa3cf4bd
Create Date: 2019-12-06 01:16:41.463730

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b98ea2a3d8ea"
down_revision = "1e4faa3cf4bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kinds", sa.Column("approved", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kinds", "approved")
    # ### end Alembic commands ###
