"""empty message

Revision ID: baa58f9b173a
Revises: 46d5ff426c51
Create Date: 2020-09-18 20:35:41.502875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "baa58f9b173a"
down_revision = "46d5ff426c51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops_to_price", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("shops_to_price", sa.Column("modified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops_to_price", "modified_at")
    op.drop_column("shops_to_price", "created_at")
    # ### end Alembic commands ###
