"""empty message

Revision ID: c7430c5fca52
Revises: f6124f577467
Create Date: 2020-05-26 17:22:41.458809

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7430c5fca52"
down_revision = "f6124f577467"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("customer_order_id", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "notes")
    op.drop_column("orders", "customer_order_id")
    # ### end Alembic commands ###
