"""empty message

Revision ID: d5b0fe563e16
Revises: d88fa9a45c17
Create Date: 2019-09-17 19:29:55.857633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d5b0fe563e16"
down_revision = "d88fa9a45c17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices_to_shops", sa.Column("use_five", sa.Boolean(), nullable=True))
    op.add_column("prices_to_shops", sa.Column("use_half", sa.Boolean(), nullable=True))
    op.add_column("prices_to_shops", sa.Column("use_joint", sa.Boolean(), nullable=True))
    op.add_column("prices_to_shops", sa.Column("use_one", sa.Boolean(), nullable=True))
    op.add_column("prices_to_shops", sa.Column("use_piece", sa.Boolean(), nullable=True))
    op.execute("ALTER TABLE prices ALTER COLUMN internal_product_id TYPE integer USING internal_product_id::integer")
    op.drop_column("prices_to_shops", "joint")
    op.drop_column("prices_to_shops", "half")
    op.drop_column("prices_to_shops", "one")
    op.drop_column("prices_to_shops", "piece")
    op.drop_column("prices_to_shops", "five")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices_to_shops", sa.Column("five", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("prices_to_shops", sa.Column("piece", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("prices_to_shops", sa.Column("one", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("prices_to_shops", sa.Column("half", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("prices_to_shops", sa.Column("joint", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column("prices_to_shops", "use_piece")
    op.drop_column("prices_to_shops", "use_one")
    op.drop_column("prices_to_shops", "use_joint")
    op.drop_column("prices_to_shops", "use_half")
    op.drop_column("prices_to_shops", "use_five")
    # ### end Alembic commands ###
