"""empty message

Revision ID: dc089ecc2c38
Revises: 9d8fc446eec1
Create Date: 2019-09-25 00:46:18.814508

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "dc089ecc2c38"
down_revision = "9d8fc446eec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shops_name", table_name="shops")
    op.create_index(op.f("ix_shops_name"), "shops", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shops_name"), table_name="shops")
    op.create_index("ix_shops_name", "shops", ["name"], unique=True)
    # ### end Alembic commands ###
