"""empty message

Revision ID: f4c17616f611
Revises: be9984e9e6b6
Create Date: 2019-08-27 13:13:44.568640

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f4c17616f611"
down_revision = "be9984e9e6b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("unit", sa.String(length=255), nullable=True))
    op.add_column("products", sa.Column("internal_product_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "internal_product_id")
    op.drop_column("prices", "unit")
    # ### end Alembic commands ###
