"""empty message

Revision ID: f6124f577467
Revises: 5f89f26268da
Create Date: 2020-05-20 16:01:30.048657

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6124f577467"
down_revision = "5f89f26268da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strains",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strains_id"), "strains", ["id"], unique=False)
    op.create_index(op.f("ix_strains_name"), "strains", ["name"], unique=True)
    op.add_column("kinds", sa.Column("strain1_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("kinds", sa.Column("strain2_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f("ix_kinds_strain1_id"), "kinds", ["strain1_id"], unique=False)
    op.create_index(op.f("ix_kinds_strain2_id"), "kinds", ["strain2_id"], unique=False)
    op.create_foreign_key(None, "kinds", "strains", ["strain1_id"], ["id"])
    op.create_foreign_key(None, "kinds", "strains", ["strain2_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "kinds", type_="foreignkey")
    op.drop_constraint(None, "kinds", type_="foreignkey")
    op.drop_index(op.f("ix_kinds_strain2_id"), table_name="kinds")
    op.drop_index(op.f("ix_kinds_strain1_id"), table_name="kinds")
    op.drop_column("kinds", "strain2_id")
    op.drop_column("kinds", "strain1_id")
    op.drop_index(op.f("ix_strains_name"), table_name="strains")
    op.drop_index(op.f("ix_strains_id"), table_name="strains")
    op.drop_table("strains")
    # ### end Alembic commands ###
